### ISSUE TITLE
Ways to support development

### ISSUE THREAD

**Issue by RicochetYT** [andro2157/DiscordTokenProtector#18]
Hi again, I've used DTP for a while now, and I've really appreciated the effort you've put into maintaining it, and would love to support you in some way! You should totally put ways to donate in your readme and stuff!

Oh yea, I'd also love if you'd sign up for [Brave Rewards](https://publishers.basicattentiontoken.org/), that way I can just toss you whatever I earn from using this browser.
Thanks for your work!

**Comment by andro2157** [comment]
Hello,

I signed up for Brave Rewards, so I should be able to receive tips from Brave; I also updated the README.

Thank you very much for using DTP and supporting the project! I'm very happy to know that DTP is useful!

**Comment by RicochetYT** [comment]
No problem! Went ahead and sent a tip that way, thank you for your work!
