### ISSUE TITLE
It doesn't detect my token.

### ISSUE THREAD

**Issue by krisztian2112** [andro2157/DiscordTokenProtector#19]
I did everything that was needed, but for some reason it didn't detect my discord token so i made a ticket.

**Comment by andro2157** [comment]
Hello,

Could you tell me what version of Windows are you running ? And what antivirus you're using ?
Have you tried logging out and back from  Discord ?

I'll try to see if I can reproduce that issue. Meanwhile, if the problem persists you can try to remove the "Local Storage" folder in `%appdata%\Discord` and log back into Discord. (This will remove local settings, but keep in mind that this also happens with the protector)

**Comment by krisztian2112** [comment]
Hi,

My windows version is 21H2. I don't use any antivirus exept windows defender. And i have tried logging out from discord, but it did not help. Sorry for the late reply, i was not home.

**Comment by andro2157** [comment]
Hello,

Have you tried deleting the `%appdata%\discord\Local Storage` folder?
I'm unable to reproduce that issue, it might be due to the leveldb database being old and storing old token format.
Currently, the only solution to this is to reset the leveldb database by removing the `Local Storage` folder.

**Comment by myuseristaken** [comment]
its asking me for a password

**Comment by andro2157** [comment]
> its asking me for a password

Hello,

Are you talking about Discord when launching? If so does it happen after rebooting your device? And can you try removing the token from DTP, and adding it back?

If the problem persists, please open a new issue.
