### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by v6r** [andro2157/DiscordTokenProtector#21]
Hey, 
I have a suggestion. I use a custom .ico for Discord to get another image in my Taskbar. I want to scan Discord before i launch it. Problem it detects my app.ico everytime as invalid hash.

Suggestion: You can put a path or smth else in the settings so this file didnt get scanned.

Hope you can help me and find a solution. Would be nice.
Also very nice work : )

**Comment by andro2157** [comment]
Hey,

Thank you!
I added this as an option under the integrity check settings in the latest release.
