### ISSUE TITLE
App resets when there is no internet connection

### ISSUE THREAD

**Issue by StrawBerryBeauty** [andro2157/DiscordTokenProtector#24]
**Describe the bug**
My router wasn't turned on when I booted my PC so when DTP opened it obviously failed to log in. As a result, it said there was a problem (I can't remember the message) so I had to redo the steps to log my account (open discord, login then close discord).

**To Reproduce**
1. Open DTP (and Discord I guess?) without internet connection

**Expected behavior**
I was expecting the app to just wait until I have internet.

**Setup:**
- Windows 10 21H2 19044.1526
- Discord Token Protector dev-8

**Comment by andro2157** [comment]
Thank you for reporting the issue!

I was able to reproduce it and I'll try to fix it next week as I don't have much time currently.
