### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by Sagvi** [andro2157/DiscordTokenProtector#25]
1. Detection doesn't work
2. 
![image](https://user-images.githubusercontent.com/91565408/156930193-e649859d-a972-4568-9ed6-1036fbff6000.png)
3. 16:35:48.014 [WARNING] Failed to find Discord in C:\Users\Saga\AppData\Local\DiscordCanary\ : directory_iterator::directory_iterator: The system cannot find the path specified.: "C:\Users\x\AppData\Local\DiscordCanary\"
16:35:48.017 [ERROR] Failed to load config : invalid JSON. [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
16:35:48.017 [WARNING] Using default config!
16:36:19.255 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.318 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.364 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.412 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.460 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.508 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.540 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.572 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.619 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.683 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.735 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.797 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.844 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.891 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.922 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:19.985 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.047 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.094 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.141 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.203 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.266 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.313 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.360 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.776 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.808 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.839 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.901 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:20.965 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:21.013 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:21.061 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:21.109 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:21.156 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:21.187 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:21.235 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:21.283 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:21.331 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:21.379 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:21.663 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:21.943 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:22.235 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:22.535 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:22.836 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:23.136 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:23.429 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:23.704 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:24.000 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:24.282 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:24.569 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:24.867 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:25.138 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:25.435 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:25.722 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:26.020 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:26.317 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:26.602 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:26.898 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:26.953 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.000 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.046 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.093 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.125 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.156 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.203 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.265 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.312 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.359 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.406 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.468 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.531 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.578 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.636 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.683 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.730 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.777 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.824 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.886 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.949 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:27.996 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.043 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.089 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.136 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.199 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.246 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.293 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.339 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.402 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.464 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.511 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.558 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.605 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:28.897 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:29.185 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:29.483 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:29.758 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:30.053 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:30.345 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:30.622 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:30.687 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:30.750 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:30.801 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:30.865 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:30.913 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:30.961 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.018 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.064 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.111 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.159 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.191 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.239 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.286 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.333 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.380 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.427 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.458 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.489 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.536 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.583 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:31.864 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:32.146 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:32.427 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:32.708 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:32.989 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:33.053 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:33.345 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:33.634 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:33.934 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:34.232 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:34.515 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:34.800 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:35.087 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:35.359 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:35.639 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:35.918 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:36.220 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:36.520 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:36.820 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:37.107 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:37.398 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:37.684 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:37.966 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.006 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.069 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.131 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.178 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.225 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.256 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.303 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.350 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.397 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.444 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.491 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.553 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:38.846 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:39.132 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:39.405 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:39.701 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:39.998 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:40.281 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:40.563 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:40.850 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.137 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.423 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.487 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.553 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.615 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.662 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.709 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.770 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.833 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.880 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.927 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.958 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:41.989 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:42.036 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:42.099 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:42.146 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:42.177 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:42.224 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:42.286 [WARNING] Unable to get the secure encryption type : the file is too short.
16:36:44.098 [WARNING] Tried to stop the protection when it's already stopped.

**Comment by andro2157** [comment]
I'll try to reproduce the issue next week as I don't have much time currently!

**Comment by andro2157** [comment]
Seems like they are deploying token encryption in the leveldb, that's interesting. That explains why DTP is unable to get the token with the current method.
I'll add another way to get the token next week.

Note: This update doesn't make DTP useless as it still protects you from script injection and memory reading.

**Comment by MrDiamond64** [comment]
> Seems like they are deploying token encryption in the leveldb, that's interesting. That explains why DTP is unable to get the token with the current method.
> 
> I'll add another way to get the token next week.
> 
> 
> 
> Note: This update doesn't make DTP useless as it still protects you from script injection and memory reading.

would it be possible to manually insert our token?

**Comment by andro2157** [comment]
Fixed in dev-9, thank you for your patience!
