### ISSUE TITLE
There any chance i can get beta access?

### ISSUE THREAD

**Issue by hrsk12** [andro2157/DiscordTokenProtector#31]
Well my Discord Not really works for me with the Discord token protector have many bugg and wanna ask about I can get beta please.

Moderator#1337

**Comment by fritzhaxx** [comment]
Just say what are the bugs

**Comment by andro2157** [comment]
Please report the bugs in this repo issue.
There are no beta versions.

**Comment by hrsk12** [comment]
i don't have any issue anymore i fixed with reinstalled discord & discord token protector

**Comment by hrsk12** [comment]
but the old issue can't find the account/token can't Load cuz password say Invalid idk why and last one if i login the discord all volume of all my friend etc get into the normal
