### ISSUE TITLE
Bug detection token

### ISSUE THREAD

**Issue by Yumeko-Dev** [andro2157/DiscordTokenProtector#34]
**Describe the bug**
token not detected the app search in discord canary and i have discord ptb

**To Reproduce**
1. Launch the exe 
2. quit discord
3. good

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
- OS Version and build: windows 10 Home 1809
- Discord Token Protector Version dev-8
- Antivirus Windows Defender (disabled)

**Logs:**
I14:33:57.154 [WARNING] Failed to find Discord in C:\Users\Yumeko\AppData\Local\DiscordCanary\ : directory_iterator::directory_iterator: The system cannot find the path specified.: "C:\Users\Yumeko\AppData\Local\DiscordCanary\"
14:33:57.156 [ERROR] Failed to load config : invalid JSON. [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
14:33:57.156 [WARNING] Using default config!
14:35:23.815 [WARNING] Tried to stop the protection when it's already stopped.
14:35:27.504 [WARNING] Failed to find Discord in C:\Users\Yumeko\AppData\Local\DiscordCanary\ : directory_iterator::directory_iterator: The system cannot find the path specified.: "C:\Users\Yumeko\AppData\Local\DiscordCanary\"
14:35:27.506 [INFO] Loaded config
14:36:28.420 [WARNING] Unable to get the secure encryption type : the file is too short.
14:36:28.704 [WARNING] Unable to get the secure encryption type : the file is too short.
14:36:28.987 [WARNING] Unable to get the secure encryption type : the file is too short.
14:36:29.270 [WARNING] Unable to get the secure encryption type : the file is too short.
14:36:29.553 [WARNING] Unable to get the secure encryption type : the file is too short.
14:36:29.837 [WARNING] Unable to get the secure encryption type : the file is too short.
14:36:30.120 [WARNING] Unable to get the secure encryption type : the file is too short.
14:36:30.403 [WARNING] Unable to get the secure encryption type : the file is too short.
14:36:30.687 [WARNING] Unable to get the secure encryption type : the file is too short.
14:36:30.970 [WARNING] Unable to get the secure encryption type : the file is too short.
14:36:31.253 [WARNING] Unable to get the secure encryption type : the file is too short.
14:36:31.537 [WARNING] Unable to get the secure encryption type : the file is too short.

**Comment by andro2157** [comment]
Hello,
Canary and PTB versions are not supported! Check #26 for updates.
The issue with the token detection has been fixed in the latest version
