### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by intesticle** [andro2157/DiscordTokenProtector#37]
token protector beaks better discord?? Even tho i have allow better discord on.
Im wondering if you can fix it or how to fix it
![image](https://user-images.githubusercontent.com/91514968/160723856-3c3786a4-defb-4f9b-8514-d43c7f64fe80.png)

**Comment by fritzhaxx** [comment]
Use Discord Stable from https://discord.com/

**Comment by rikuzx** [comment]
> Use Discord Stable from https://discord.com/

i dont really like stable discord i use better discord is there a fix for this tho?

**Comment by fritzhaxx** [comment]
DTP isn't available for Better Discord

**Comment by variablenine** [comment]
i have the token protector on with betterdiscord and it seems to work fine most of the time. if betterdiscord crashes discord tho, DTP doesn't know what to do and forces betterdiscord to keep crashing discord. most of the time I just have to turn off protection until a convenient time i can restart my computer. really sucks that i cant just do a quick ctrl+r when i have it enabled

**Comment by andro2157** [comment]
> token protector beaks better discord?? Even tho i have allow better discord on. Im wondering if you can fix it or how to fix it ![image](https://user-images.githubusercontent.com/91514968/160723856-3c3786a4-defb-4f9b-8514-d43c7f64fe80.png)

Can you develop what DTP breaks?
The "Allow BetterDiscord" checkbox allows the BetterDiscord injection script to be loaded

**Comment by andro2157** [comment]
> token protector beaks better discord?? Even tho i have allow better discord on. Im wondering if you can fix it or how to fix it ![image](https://user-images.githubusercontent.com/91514968/160723856-3c3786a4-defb-4f9b-8514-d43c7f64fe80.png)

Can you develop what DTP breaks?
The "Allow BetterDiscord" checkbox allows the BetterDiscord injection script to be loaded
