### ISSUE TITLE
Really bad compatibility with BetterDiscord

### ISSUE THREAD

**Issue by variablenine** [andro2157/DiscordTokenProtector#39]
**Describe the bug**
When BetterDiscord crashes the client, DTP doesn't respond very well and repeatedly crashes the client over and over until I turn off protection or restart my computer.

**To Reproduce**
1. Install BetterDiscord
2. Load a bunch of plugins
3. Wait for it to crash
4. DTP will then repeatedly close and reopen discord with the error message saying that BetterDiscord crashed the client and doesn't stop until you turn off protection.

**Expected behavior**
I was hoping like some sort of message on the token protector window saying that Discord crashed and then a button to restart Discord that would essentially end the Discord process and restart it completely.

**Screenshots**
I can't reproduce it at will bc BetterDiscord crashes randomly

**Setup (please complete the following information):**
- OS Version and build: Windows 11 21H2 22000.613
- Discord Token Protector Version dev-9
- Windows Defender

**Logs:**
List of recent relevant logs:
14:37:46.187 [WARNING] Failed to find Discord in C:\Users\Colli\AppData\Local\DiscordCanary\ : directory_iterator::directory_iterator: The system cannot find the path specified.: "C:\Users\Colli\AppData\Local\DiscordCanary\"
14:37:46.188 [ERROR] Failed to load config : invalid JSON. [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
14:37:46.188 [WARNING] Using default config!
14:40:38.062 [ERROR] Failed to load secure : file is empty
14:40:38.067 [INFO] Loaded config
14:40:38.068 [INFO] Loaded config
14:40:38.068 [INFO] Loaded config
14:40:44.402 [INFO] auto __thiscall Discord::killDiscord::<lambda_507bee90b6de1e7e5034771acc9a54d6>::()::<lambda_19013b087c165c6a476b3a938d66bdc8>::operator ()(void) const : Terminated process. pid : 1780
14:40:44.744 [ERROR] auto __thiscall Discord::killDiscord::<lambda_507bee90b6de1e7e5034771acc9a54d6>::operator ()(const class std::vector<unsigned long,class std::allocator<unsigned long> > &) const : Failed to terminate process. pid : 14144
14:40:44.744 [ERROR] auto __thiscall Discord::killDiscord::<lambda_507bee90b6de1e7e5034771acc9a54d6>::operator ()(const class std::vector<unsigned long,class std::allocator<unsigned long> > &) const : Failed to get process info. pid : 8384
14:40:44.744 [ERROR] auto __thiscall Discord::killDiscord::<lambda_507bee90b6de1e7e5034771acc9a54d6>::operator ()(const class std::vector<unsigned long,class std::allocator<unsigned long> > &) const : Failed to get process info. pid : 12252
14:40:44.744 [ERROR] auto __thiscall Discord::killDiscord::<lambda_507bee90b6de1e7e5034771acc9a54d6>::operator ()(const class std::vector<unsigned long,class std::allocator<unsigned long> > &) const : Failed to get process info. pid : 9192
14:40:44.745 [ERROR] auto __thiscall Discord::killDiscord::<lambda_507bee90b6de1e7e5034771acc9a54d6>::operator ()(const class std::vector<unsigned long,class std::allocator<unsigned long> > &) const : Failed to get process info. pid : 6324
14:41:21.597 [INFO] Accept!
14:41:21.674 [INFO] port : 54359
14:41:21.889 [INFO] setport : 1458120304
14:41:21.890 [INFO] done
14:41:21.904 [INFO] Accepted : 2376
14:41:36.031 [INFO] Accepted handoff!
14:41:38.696 [INFO] set Discord security info!
14:45:16.463 [ERROR] void __thiscall Context::networkHandler(void) : class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall NetworkManager::Recv(void) : Failed recv : -1 10054
14:45:44.968 [INFO] auto __thiscall Discord::killDiscord::<lambda_507bee90b6de1e7e5034771acc9a54d6>::()::<lambda_19013b087c165c6a476b3a938d66bdc8>::operator ()(void) const : Terminated process. pid : 12720

**Additional context**
I'm aware that it wasn't originally designed to be compatible with BetterDiscord but a good chunk of people using a token protector are also likely using it, so compatibility should be a pretty big priority to make sure the two programs can work in unison.

**Comment by andro2157** [comment]
Hello,

When you're talking about a crash, are you talking about this kind of crash?
![lnz9GLNuhhbbEve8ghF1AA](https://user-images.githubusercontent.com/29313387/164890223-6638181f-5490-46e0-adbd-fbf10d9e5e5d.png)

If so, reloading doesn't cause any issue on my side.
By the way, you said that you weren't able to do a ctrl-r, could you explain what happens when you do so? I'm unable to reproduce these issues as it seems to work fine on my side.

**Comment by andro2157** [comment]
Hello,

When you're talking about a crash, are you talking about this kind of crash?
![lnz9GLNuhhbbEve8ghF1AA](https://user-images.githubusercontent.com/29313387/164890223-6638181f-5490-46e0-adbd-fbf10d9e5e5d.png)

If so, reloading doesn't cause any issue on my side.
By the way, you said that you weren't able to do a ctrl-r, could you explain what happens when you do so? I'm unable to reproduce these issues as it seems to work fine on my side.

**Comment by variablenine** [comment]
No, I'm talking about this crash.

https://user-images.githubusercontent.com/103234275/164998472-d3fe19ac-26fb-42bb-8114-626a2c5596ea.mp4

That happens repeatedly without me even having to touch anything, and it doesn't stop happening until I turn off protection in DTP. Then I have to restart my entire computer to get the protection up and running again. It runs smoothly until discord randomly crashes like that.

**Comment by variablenine** [comment]
I've had it off since I got it. I have BetterDiscord bogged down with a lot of plugins so it randomly crashes every once in a while, I can't make that happen. Normally I have to be using discord for a few hours before it happens, but I'll comment with the log again the next time it happens.
