### ISSUE TITLE
Unable to find token in memory

### ISSUE THREAD

**Issue by ElectroYModz** [andro2157/DiscordTokenProtector#41]
![image](https://user-images.githubusercontent.com/44715385/167261234-76b4677d-dfa6-4a2b-8b13-cf82dc70e068.png)
I am getting this and i checked logs and all i see is just 
11:32:50.672 [INFO] Loaded config
and nothing else

it happened after enabling 2FA

**Comment by AzureAzel** [comment]
Same issue here, Did a fresh install of Windows and it suddenly can't get my token anymore. I tried disabling windows defender in case it was interfering, and I had no luck.

**Comment by AzureAzel** [comment]
I did some digging, and it seems like a recent Discord update is what's causing this. They now encrypt your token with the same encryption as chrome passwords. While it's a nice touch, it isn't nearly as secure as this application has been. It just takes a bit extra effort to decrypt it.

**Comment by fritzhaxx** [comment]
Did you use discord stable?

**Comment by andro2157** [comment]
> I did some digging, and it seems like a recent Discord update is what's causing this. They now encrypt your token with the same encryption as chrome passwords. While it's a nice touch, it isn't nearly as secure as this application has been. It just takes a bit extra effort to decrypt it.

Well DTP was updated to support this change. This problem might be due to a new Discord token format

**Comment by andro2157** [comment]
Can you try the dev-9-fix update?

**Comment by AzureAzel** [comment]
> 

Just tested it. Works for me now. Thanks for working on this, by the way. It's been a literal lifesaver.

**Comment by andro2157** [comment]
Glad it helped!
