### ISSUE TITLE
[ Suggestion ] Add an minimize feature

### ISSUE THREAD

**Issue by RealLinen** [andro2157/DiscordTokenProtector#42]
Add a minimize feature to minimize the app to the background [ so it doeesn't show in the taskbar, but shows in those little list of icons ]
I think this app is great, Thanks!

**Comment by fritzhaxx** [comment]
Isn't that already added? You just need to close with the button and it will minimize afaik

**Comment by LeeWen0802** [comment]
It's already there
Just use the button that close window, it will still run in background

**Comment by andro2157** [comment]
As said above, it's already implemented
