### ISSUE TITLE
This token grabber disables you token protector

### ISSUE THREAD

**Issue by Mrgaton** [andro2157/DiscordTokenProtector#43]
https://github.com/Rdimo/Hazard-Token-Grabber-V2/blob/master/main.py

**Comment by LeeWen0802** [comment]
ye, as we said, there's no perfect solution.
if you want to avoid token loggers, best way you can do is run suspicious program in sandbox, or just simply don't run it

**Comment by fritzhaxx** [comment]
Is it working and really killing DTP? 🤔
If it does, it will just be obvious that a program tried to grab you (because DTP got closed, and Discord restarted asking you to login again)
What you will have to do is just enable DTP again after removing the injector in Discord src.

**Comment by LeeWen0802** [comment]
but some people wont notice something inject into their Discord app

**Comment by fritzhaxx** [comment]
Well... If discord closes and DTP too it will seem a bit suspicious

**Comment by fritzhaxx** [comment]
Yes, but if you started a py2exe file and your discord & DTP crashes, and then discord asks you for your login, it's obv that something got injected in your discord src, so just go reinstall discord an problem solved

**Comment by LeeWen0802** [comment]
> Yes, but if you started a py2exe file and your discord & DTP crashes, and then discord asks you for your login, it's obv that something got injected in your discord src, so just go reinstall discord an problem solved

agree

**Comment by dekrypted** [comment]
Another thing to note is that since there's no info stored for it to access, the only way the attacker could get your info is by having you log in again. So, you could just reset the DTP Config, remove the injection, and be good to go!
