### ISSUE TITLE
Password Error

### ISSUE THREAD

**Issue by WulferGaming** [andro2157/DiscordTokenProtector#45]
When I start Discord Token Protector after a Windows restart I need to enter the Password and when I enter the Password they say's that the Password was Wrong

1. Install DTP and set only a Password
2. Go to the settings and set "ignore .ico", "BetterDiscord", "Start with Windows"
3.  Restart Windows and enter the Password.

- OS Version and build: Windows 11 | 21H2
- Discord Token Protector Version dev-9
- Antivirus Kaspersky

*Log*
[logging.log](https://github.com/andro2157/DiscordTokenProtector/files/8672740/logging.log)

**Comment by WulferGaming** [comment]
My Encryption method is only Password

**Comment by andro2157** [comment]
Did you put any non-alphanumerical characters in the password?

**Comment by WulferGaming** [comment]
In my Password are Letters, Numbers and #. I had already tried it with a reinstallation that was successful, then I made a Password with only letters & Number and that hadn't work.

**Comment by andro2157** [comment]
Currently, I have no idea why it is causing this, and I'm unable to reproduce the issue. I'll reply to this issue if I find the cause.
Could you still try to put a very simple password like "12345678"?

**Comment by WulferGaming** [comment]
A very simple Password only with Numbers works, but when I do letters and Numbers that didn't work.

**Comment by andro2157** [comment]
Oh, do you by any chance use a non-english/qwerty keyboard? Did you use special characters (with accents for example)?

**Comment by WulferGaming** [comment]
I had a German keyboard, but I didn't use Special letters like ö or ä.

**Comment by b6m** [comment]
same thing is happening to me..

**Comment by HyCore** [comment]
same thing to me, but it can be reproduce by purposely shutting down the computer, for example when the PC crash. After a restart it won't work anymore.
