### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Random3131** [andro2157/DiscordTokenProtector#46]
I don't know if its possible or not but if it is, then can u make a option so that it would open when u open discord automatically and close when we close discord.

**Comment by andro2157** [comment]
Hello,
To detect that Discord is running, DTP would still have to be running in the background.
And even if I could, I wouldn't add this feature as it could make your Discord token vulnerable (localstorage not being removed, DTP tampered, ...)

But currently what you can do is to let DTP start with Windows and keep it running in the background, it should be disturbing and uses basically 0% CPU.

**Comment by Random3131** [comment]
okk thanks
