### ISSUE TITLE
Kaspersky false Trojan detect

### ISSUE THREAD

**Issue by WulferGaming** [andro2157/DiscordTokenProtector#47]
Kasperksy Anti-Virus thinks that DTP is/has a Trojan build in the Software

1. Kaspersky Total Security Started with Windows etc.
2. try to Install DTP

- OS Version and build: Windows 11 | 21H2
- Discord Token Protector Version dev-9
- Antivirus Kaspersky Total Security

**Comment by andro2157** [comment]
Hello,
Many AVs indeed falsely flag DTP as malware as it does suspicious activities.
I reported the false flag, but I cannot guarantee that they're going to remove it.

(Similar issue #40 )
