### ISSUE TITLE
Grabbers being able to change DTP config to bypass?

### ISSUE THREAD

**Issue by xFGhoul** [andro2157/DiscordTokenProtector#49]
title says it all, in one of the most popular token grabbers hazard grabber they simply remove the files and change the config:

https://github.com/Rdimo/Hazard-Token-Grabber-V2/blob/b255dd6967fd61a2c381321fdcdb0aaaa3c41f43/main.py#L236

is there anything being done/has been done to fix this?

**Comment by andro2157** [comment]
Hi,
This grabber doesn't bypass DTP. It cannot get the token from DTP.
The only thing it does only works if it is ran as admin or if DTP is not running. It just tries to remove/tamper DTP. (Note that sensitive configs like the integrity check have been moved to the secure container, so most of the config change is useless).

Therefore, if you keep DTP running in the background and that you don't run suspicious stuff as admin, you're fine.

**Comment by xFGhoul** [comment]
oh alright, neat
