### ISSUE TITLE
(BetterDiscord) DTP resets my discord settings every launch

### ISSUE THREAD

**Issue by Dadik11** [andro2157/DiscordTokenProtector#53]
**Describe the bug**
Discord settings reset

**To Reproduce**
1. set some settings
2. reboot pc
3. launch DTP, input password, launch discord, boom settings reset

**Expected behavior**
Settings stay the same

**Screenshots**

**Setup (please complete the following information):**
- Windows 10 home Version 10.0.19043 Build 19043
- Discord Token Protector Version dev-10
- Antivirus only Windows Defender

**Logs:**
Is there a file called "logging.log" in `%appdata%\DiscordTokenProtector` ? If so can you send it here?
Yes, attached to this issue

**Additional context**
[logging.log](https://github.com/andro2157/DiscordTokenProtector/files/9071949/logging.log)

**Comment by sbeeo** [comment]
https://github.com/andro2157/DiscordTokenProtector#some-stuff-to-consider
its the first thing there.
