### ISSUE TITLE
Discord Token Login

### ISSUE THREAD

**Issue by AltyKing** [andro2157/DiscordTokenProtector#56]
Did you know that discord has a token protector
sort of
just turn on 2fa and nobody can login in with token lmao

you're trash kid

**Comment by fritzhaxx** [comment]
Yo, https://streamable.com/81y466

**Comment by AltyKing** [comment]
> https://streamable.com/81y466

WHAT THE FUCK

**Comment by andro2157** [comment]
Hi, as seen above that information is totally wrong.

Btw, it's also kinda trashy to spread grabbers and rats through your fake Discord "hacking console".

[Rat that have been deleted](https://github.com/AltyKing/Tabby-Terminal/blob/3ccd7d306e769f10605f9b68912f6151e15b4f0a/Data-Bridge.exe) (you forgot to squash your commits ?)
[Anyrun analysis](https://app.any.run/tasks/632babac-6b11-40a6-bf3d-2b936efe9a0b)
![image](https://user-images.githubusercontent.com/29313387/187044565-a75bb73e-3e47-4b28-be57-5047b58b66f2.png)

Oh and yeah your pyinstaller python grabbers...

![image](https://user-images.githubusercontent.com/29313387/187044575-0d2f1be5-2328-493f-9b0b-e51ec2c7d98b.png)
![image](https://user-images.githubusercontent.com/29313387/187044579-63d9018f-5043-446c-a8a8-926fc55b6a1b.png)
![image](https://user-images.githubusercontent.com/29313387/187044742-f7c9138b-b8eb-47e5-a998-0607ec6cc689.png)
![image](https://user-images.githubusercontent.com/29313387/187044580-03443c7b-6853-4349-9454-ebb8771247f4.png)

```
https://discord.com/api/webhooks/1010151763854233650/Ryd7E_7reLipzEC3xBmlcY_TcMZ_Zz1QT_Uy44F_VobnqD9xnFxuyKX8SLJslJLKBiPl
https://discord.com/api/webhooks/1002562051408928838/4T2AEFeebQ9uM4KOlHamn1b9Hn5eishW6X6ehcMsemIcD3YEcsqifbvrK7598GZcg9K6
https://discord.com/api/webhooks/1010873178924523560/DmbhA6la8H8SunALy8-hagDUAg_B9KpJQhGRH-p8B86v70cdNtKBbxSZfBJ92W161erh
```

**Comment by AltyKing** [comment]
> Hi, as seen above that information is totally wrong.
> 
> Btw, it's also kinda trashy to spread grabbers and rats through your fake Discord "hacking console".
> 
> [Rat that have been deleted](https://github.com/AltyKing/Tabby-Terminal/blob/3ccd7d306e769f10605f9b68912f6151e15b4f0a/Data-Bridge.exe) (you forgot to squash your commits ?) [Anyrun analysis](https://app.any.run/tasks/632babac-6b11-40a6-bf3d-2b936efe9a0b) ![image](https://user-images.githubusercontent.com/29313387/187044565-a75bb73e-3e47-4b28-be57-5047b58b66f2.png)
> 
> Oh and yeah your pyinstaller python grabbers...
> 
> ![image](https://user-images.githubusercontent.com/29313387/187044575-0d2f1be5-2328-493f-9b0b-e51ec2c7d98b.png) ![image](https://user-images.githubusercontent.com/29313387/187044579-63d9018f-5043-446c-a8a8-926fc55b6a1b.png) ![image](https://user-images.githubusercontent.com/29313387/187044742-f7c9138b-b8eb-47e5-a998-0607ec6cc689.png) ![image](https://user-images.githubusercontent.com/29313387/187044580-03443c7b-6853-4349-9454-ebb8771247f4.png)
> 
> ```
> https://discord.com/api/webhooks/1010151763854233650/Ryd7E_7reLipzEC3xBmlcY_TcMZ_Zz1QT_Uy44F_VobnqD9xnFxuyKX8SLJslJLKBiPl
> https://discord.com/api/webhooks/1002562051408928838/4T2AEFeebQ9uM4KOlHamn1b9Hn5eishW6X6ehcMsemIcD3YEcsqifbvrK7598GZcg9K6
> https://discord.com/api/webhooks/1010873178924523560/DmbhA6la8H8SunALy8-hagDUAg_B9KpJQhGRH-p8B86v70cdNtKBbxSZfBJ92W161erh
> ```

its tabby terminal now lol
