### ISSUE TITLE
Encrypting... lasts forever?

### ISSUE THREAD

**Issue by CycloneCX** [andro2157/DiscordTokenProtector#63]
Encryption... lasts forever.

**Comment by CycloneCX** [comment]
Anyway to make it save the Discord settings? They reset to default every single time I use this software, would love to have my cake and eat it too (encryption issue was solved by selecting much lower has time).

**Comment by CycloneCX** [comment]
Please, this tool is perfect with the only issue being discord not saving. @andro2157

**Comment by andro2157** [comment]
Hello,
Sorry for late reply.
About the Discord settings for being saved, it is due to the fact that DTP removes the local database used by Discord to store them (and the token).
This is one of the measures to protect your token and won't be changed any time soon, sorry
