### ISSUE TITLE
App Crash causes unremovable tray icon

### ISSUE THREAD

**Issue by Aperre** [andro2157/DiscordTokenProtector#67]
**Describe the bug**
If the program crashes or freezes in the starting state the tray icon never gets removed

**To Reproduce**
1. Simulate a crash: When the state is "Starting..." force close with task manager
2. The tray icon is still there

**Expected behavior**
The tray icon gets removed after crash

**Screenshots**
![image](https://user-images.githubusercontent.com/60411288/224524701-0dcb726a-5652-4b99-b2b2-d298aa25ae3c.png)

**Setup (please complete the following information):**
- Discord Token Protector Version dev-11

**Comment by andro2157** [comment]
Hello,
This is an expected behavior if there's a crash, as it doesn't call the function to remove the tray icon before closing.
Moving your mouse over the invalid icons should remove them.
This is a "bug" in Windows and happens for other softwares too.
