### ISSUE TITLE
Some error 

### ISSUE THREAD

**Issue by kingsman12212** [andro2157/DiscordTokenProtector#7]
Hi im not able to get this shit idk why but u can help me with this ?

![image](https://user-images.githubusercontent.com/80263858/125320741-a08b2480-e359-11eb-8c25-c54eb766c299.png)

**Comment by andro2157** [comment]
Hello,

You first need to download Polyhook2,  CryptoPP, and CUrl

https://github.com/stevemk14ebr/PolyHook_2_0
https://www.cryptopp.com/#download
https://curl.se/download.html

Then, in the project properties, you'll need to add these folders to the includes:
* `PolyHook_2_0\polyhook2`
* `PolyHook_2_0\capstone`
* a folder containing the content of cryptopp
* a folder containing the include of CUrl

You might need to readd the headers and cpp files from these libraries in the solution explorer.

You'll also need to compile PolyHook and CUrl as static libraries (.lib) and include them in the project.

**Comment by andro2157** [comment]
Hey,

Please check https://github.com/andro2157/DiscordTokenProtector#compilation

The compilation process has been very simplified, you no longer need to compile manually these libs
