### ISSUE TITLE
[SUGGESTION] Block scams links

### ISSUE THREAD

**Issue by zvbt** [andro2157/DiscordTokenProtector#76]
Modify the windows HOST file to block scam link using this [database](https://github.com/Discord-AntiScam/scam-links).

**Comment by pierrelasse** [comment]
Don't know if this should be done by this tool since it's made to protect you from token grabbers, not to block scam links.

**Comment by NoPlagiarism** [comment]
It's not exactly what DTP is about, so first of all. Sometimes blocking scam domain using HOSTS just can't help you. For example, when [browser using DoH](https://tinyurl.com/doh-hosts)

So if you need sth like this, you can find some uBlock filters or extensions like [NetCraft one](https://www.netcraft.com/apps-extensions/browser-extension/)

**Comment by 32bitx64bit** [comment]
I'd prefer this app not scan my messages. As it would have to do so to find these scam links. And it wouldn't even be possible to block as scam links change all the time. And are most likely not blocked by anyone.

**Comment by NoPlagiarism** [comment]
> not scan my messages

Idea was just about updating HOSTS file with scam domains from Discord-AntiScam

**Comment by pierrelasse** [comment]
There are plenty of extensions that do that and aince your are normall opening links with your browser, a extension would just do fine in blocking scam, fishing etc. links.
